apiVersion: v1
kind: Service
metadata:
  name: testing-service
spec:
  type: NodePort
  selector:
    app: testing
  ports:
  - port: 8081       # The port that the service will expose
    targetPort: 8081 # The port on the container
    nodePort: 30081  # The port on the node that you will access from outside (choose any port between 30000-32767)
